
package br.com.SystemOs.view;

import br.com.SystemOs.dal.ClienteDal;
import br.com.SystemOs.dal.OsDal;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;


public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        desktop = new javax.swing.JDesktopPane();
        lbl_nome = new javax.swing.JLabel();
        lbl_data = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        barra_menu_telaPrincipal = new javax.swing.JMenuBar();
        menu_cadastro = new javax.swing.JMenu();
        item_menu_cliente = new javax.swing.JMenuItem();
        item_menu_os = new javax.swing.JMenuItem();
        item_menu_usuario = new javax.swing.JMenuItem();
        menu_relatorio = new javax.swing.JMenu();
        item_menu_relCli = new javax.swing.JMenuItem();
        item_menu_servicos = new javax.swing.JMenuItem();
        menu_ajuda = new javax.swing.JMenu();
        item_menu_sobre = new javax.swing.JMenuItem();
        menu_opcoes = new javax.swing.JMenu();
        item_menu_sair = new javax.swing.JMenuItem();
        item_menu_vTelaInicial = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1053, 638));

        desktop.setBackground(new java.awt.Color(0, 102, 102));
        desktop.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        desktop.setPreferredSize(new java.awt.Dimension(760, 600));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lbl_nome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_nome.setText("Nome");

        lbl_data.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_data.setText("Data");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/SystemOs/icons/logo.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(256, 256));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nome)
                    .addComponent(lbl_data)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lbl_nome)
                .addGap(33, 33, 33)
                .addComponent(lbl_data)
                .addGap(133, 133, 133)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        barra_menu_telaPrincipal.setBorder(null);
        barra_menu_telaPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        menu_cadastro.setBackground(new java.awt.Color(0, 204, 204));
        menu_cadastro.setText("Cadastro");

        item_menu_cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        item_menu_cliente.setText("Cliente");
        item_menu_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_clienteActionPerformed(evt);
            }
        });
        menu_cadastro.add(item_menu_cliente);

        item_menu_os.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        item_menu_os.setText("OS");
        item_menu_os.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_osActionPerformed(evt);
            }
        });
        menu_cadastro.add(item_menu_os);

        item_menu_usuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        item_menu_usuario.setText("Usuarios");
        item_menu_usuario.setEnabled(false);
        item_menu_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_usuarioActionPerformed(evt);
            }
        });
        menu_cadastro.add(item_menu_usuario);

        barra_menu_telaPrincipal.add(menu_cadastro);

        menu_relatorio.setBackground(new java.awt.Color(0, 204, 204));
        menu_relatorio.setText("Relatório");
        menu_relatorio.setEnabled(false);

        item_menu_relCli.setText("Clientes");
        item_menu_relCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_relCliActionPerformed(evt);
            }
        });
        menu_relatorio.add(item_menu_relCli);

        item_menu_servicos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        item_menu_servicos.setText("Serviços");
        item_menu_servicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_servicosActionPerformed(evt);
            }
        });
        menu_relatorio.add(item_menu_servicos);

        barra_menu_telaPrincipal.add(menu_relatorio);

        menu_ajuda.setBackground(new java.awt.Color(0, 204, 204));
        menu_ajuda.setText("Ajuda");

        item_menu_sobre.setText("Sobre");
        item_menu_sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_sobreActionPerformed(evt);
            }
        });
        menu_ajuda.add(item_menu_sobre);

        barra_menu_telaPrincipal.add(menu_ajuda);

        menu_opcoes.setBackground(new java.awt.Color(0, 204, 204));
        menu_opcoes.setText("Opções");

        item_menu_sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        item_menu_sair.setText("Sair");
        item_menu_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_sairActionPerformed(evt);
            }
        });
        menu_opcoes.add(item_menu_sair);

        item_menu_vTelaInicial.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.ALT_MASK));
        item_menu_vTelaInicial.setText("Volta Para Tela Login");
        item_menu_vTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_vTelaInicialActionPerformed(evt);
            }
        });
        menu_opcoes.add(item_menu_vTelaInicial);

        barra_menu_telaPrincipal.add(menu_opcoes);

        setJMenuBar(barra_menu_telaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1044, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void item_menu_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_clienteActionPerformed
        
        TelaCliente cliente = new TelaCliente();
        desktop.add(cliente);
        cliente.setVisible(true);

    }//GEN-LAST:event_item_menu_clienteActionPerformed

    private void item_menu_osActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_osActionPerformed
       
        TelaOs os = new TelaOs();
        os.getNomeUser(lbl_nome.getText());
        desktop.add(os);
        os.setVisible(true);
    }//GEN-LAST:event_item_menu_osActionPerformed

    private void item_menu_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_usuarioActionPerformed
       
        TelaUsuario telaUsuario = new TelaUsuario();
        desktop.add(telaUsuario);
        telaUsuario.setVisible(true);

    }//GEN-LAST:event_item_menu_usuarioActionPerformed

    private void item_menu_relCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_relCliActionPerformed
        
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja gerar relatorio de clientes?",
            "Atenção", JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_OPTION){
            ClienteDal cd = new ClienteDal();
            cd.gerarRelatorio();
        }
    }//GEN-LAST:event_item_menu_relCliActionPerformed

    private void item_menu_servicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_servicosActionPerformed
        
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja gerar relatorio de Serviços?",
            "Atenção", JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_OPTION){
            OsDal dal = new OsDal();
            dal.gerarRelatorio();
        }
    }//GEN-LAST:event_item_menu_servicosActionPerformed

    private void item_menu_sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_sobreActionPerformed
        // TODO add your handling code here:
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_item_menu_sobreActionPerformed

    private void item_menu_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_sairActionPerformed
        
        int sair = JOptionPane.showConfirmDialog(null,
            "Tem certeza que deseja sair",
            "Atenção",JOptionPane.YES_NO_OPTION);

        if(sair == JOptionPane.YES_OPTION){
            System.exit(sair);
        }

    }//GEN-LAST:event_item_menu_sairActionPerformed

    private void item_menu_vTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_vTelaInicialActionPerformed
        
        int voltar = JOptionPane.showConfirmDialog(null,
            "Tem certeza que deseja voltar para a tela login",
            "Atenção",JOptionPane.YES_NO_OPTION);

        if(voltar == JOptionPane.YES_OPTION){
            TelaLogin login = new TelaLogin();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_item_menu_vTelaInicialActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Date date = new Date();
        DateFormat format = DateFormat.getDateInstance(DateFormat.SHORT);
        
        lbl_data.setText(format.format(date));
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barra_menu_telaPrincipal;
    public static javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem item_menu_cliente;
    private javax.swing.JMenuItem item_menu_os;
    private javax.swing.JMenuItem item_menu_relCli;
    private javax.swing.JMenuItem item_menu_sair;
    private javax.swing.JMenuItem item_menu_servicos;
    private javax.swing.JMenuItem item_menu_sobre;
    public static javax.swing.JMenuItem item_menu_usuario;
    private javax.swing.JMenuItem item_menu_vTelaInicial;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_data;
    public static javax.swing.JLabel lbl_nome;
    private javax.swing.JMenu menu_ajuda;
    private javax.swing.JMenu menu_cadastro;
    private javax.swing.JMenu menu_opcoes;
    public static javax.swing.JMenu menu_relatorio;
    // End of variables declaration//GEN-END:variables
}
