package br.com.SystemOs.view;

import br.com.SystemOs.constantes.IOs;
import br.com.SystemOs.dal.OsDal;
import br.com.SystemOs.dal.UsuarioDal;
import br.com.SystemOs.model.Cliente;
import br.com.SystemOs.model.Os;
import br.com.SystemOs.model.Usuario;
import br.com.SystemOs.table.OsTableModel;
import javax.swing.JOptionPane;

public class TelaOs extends javax.swing.JInternalFrame implements IOs {

    private static String id_os;
    private static String data_os;
    private static String tipo;
    private static String situacao;
    private static String descricao;
    private static String equipamento;
    private static String defeito;
    private static String servico;
    private static String tecnico;
    private static String valor;
    private static String idcliente;
    private static String nome;
    private static String telefone;
    private String nomeUser;

    /**
     * Creates new form TelaOs
     */
    public TelaOs() {
        initComponents();

        /*pega os nomes dos tecnicos da tabela usuario e passa paro
        o comboBox tecnico*/
        getValTecUsuario();

        OsDal dal = new OsDal();
        dal.ultimoCampo();
        obterValor();

        String sql = "select * from tbos";
        tb_os.setModel(new OsTableModel(new OsDal().listarTodos(sql)));
        
        if ((txt_os.getText().equals("")) || (txt_os.getText().equals("0"))){
            btn_alterar.setEnabled(false);
            btn_excluir.setEnabled(false);
            btn_imprimir.setEnabled(false);
        }else{
            btn_alterar.setEnabled(true);
            btn_excluir.setEnabled(true);
            btn_imprimir.setEnabled(true);
        }
    }

    private void obterValor() {
        try {
            OsDal dal = new OsDal();
            txt_os.setText(id_os);
            txt_data.setText(data_os);

            if (tipo.equals(rb_orcamento.getText())) {
                rb_orcamento.setSelected(true);
            } else {
                rb_ordem_servico.setSelected(true);
            }

            cb_situacao.setSelectedItem(situacao);
            txt_area_descricao.setText(descricao);
            txt_equipamento.setText(equipamento);
            txt_defeito.setText(defeito);
            txt_servico.setText(servico);
            cb_tecnico.setSelectedItem(tecnico);
            txt_valor_total.setText(valor);
            txt_cod_cliente.setText(idcliente);

            //dados do cliente
            dal.valorCliente(idcliente);

            txt_nome.setText(nome);
            txt_telefone.setText(telefone);
        } catch (Exception e) {
        }

    }

    public static void valor(Os os) {
        id_os = String.valueOf(os.getCodigo());
        data_os = os.getData();
        tipo = os.getTipo();
        situacao = os.getSituacao();
        descricao = os.getDescricao();
        equipamento = os.getEquipamento();
        defeito = os.getDefeito();
        servico = os.getServico();
        tecnico = os.getTecnico();
        valor = String.valueOf(os.getValor());
        idcliente = String.valueOf(os.getCod_cliente());

    }

    public static void valor(Cliente cliente) {
        nome = cliente.getNome();
        telefone = cliente.getTelefone();
    }

    private void getValTecUsuario() {

        String sql = "select * from tbusuario where cargo = 'Tecnico em Informatica' ";
        UsuarioDal usuarioDal = new UsuarioDal();
        for (Usuario u : usuarioDal.listarTodos(sql)) {
            cb_tecnico.addItem(u.getNome());
        }
    }

    public void getNomeUser(String nomeUser) {
        this.nomeUser = nomeUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_group_tipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_os = new javax.swing.JTextField();
        txt_data = new javax.swing.JTextField();
        rb_orcamento = new javax.swing.JRadioButton();
        rb_ordem_servico = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        btn_pesquisar_cliente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_cod_cliente = new javax.swing.JTextField();
        txt_nome = new javax.swing.JTextField();
        txt_telefone = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cb_situacao = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_equipamento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area_descricao = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_servico = new javax.swing.JTextField();
        txt_defeito = new javax.swing.JTextField();
        cb_tecnico = new javax.swing.JComboBox<>();
        txt_valor_total = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        txt_pesquisar = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_os = new javax.swing.JTable();
        cb_opcao = new javax.swing.JComboBox<>();
        btn_novo = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btn_salvar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btn_alterar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btn_excluir = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btn_imprimir = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nº OS");

        jLabel2.setText("Data");

        txt_os.setEnabled(false);

        txt_data.setEnabled(false);

        bt_group_tipo.add(rb_orcamento);
        rb_orcamento.setText("Orçamento");
        rb_orcamento.setEnabled(false);

        bt_group_tipo.add(rb_ordem_servico);
        rb_ordem_servico.setText("Ordem de serviço");
        rb_ordem_servico.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(rb_orcamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_os))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_data)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_ordem_servico)
                            .addComponent(jLabel2))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_os, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_orcamento)
                    .addComponent(rb_ordem_servico))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_pesquisar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/SystemOs/icons/t_procurar.png"))); // NOI18N
        btn_pesquisar_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pesquisar_cliente.setEnabled(false);
        btn_pesquisar_cliente.setPreferredSize(new java.awt.Dimension(20, 20));
        btn_pesquisar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisar_clienteActionPerformed(evt);
            }
        });

        jLabel4.setText("Cod cliente");

        jLabel5.setText("Nome");

        jLabel6.setText("Telefone");

        txt_cod_cliente.setEnabled(false);

        txt_nome.setEnabled(false);

        txt_telefone.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_cod_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_pesquisar_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_cod_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(btn_pesquisar_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cb_situacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Na bancada", "Aguardando Aprovação", "Orçamento REPROVADO", "Em manutenção", "Aguardando peças", "Abandonado pelo cliente", "Entrega OK", "Retornou" }));
        cb_situacao.setEnabled(false);

        jLabel3.setText("Situação");

        jLabel7.setText("Equipamento");

        txt_equipamento.setEnabled(false);

        jLabel8.setText("Descrição");

        txt_area_descricao.setColumns(20);
        txt_area_descricao.setRows(5);
        txt_area_descricao.setEnabled(false);
        jScrollPane1.setViewportView(txt_area_descricao);

        jLabel9.setText("Defeito");

        jLabel10.setText("Serviço");

        jLabel11.setText("Tecnico");

        jLabel12.setText("Valor Total");

        txt_servico.setEnabled(false);

        txt_defeito.setEnabled(false);

        cb_tecnico.setEnabled(false);

        txt_valor_total.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        txt_valor_total.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_equipamento)
                    .addComponent(txt_servico)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cb_situacao, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addComponent(cb_tecnico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(txt_defeito)
                    .addComponent(txt_valor_total, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cb_situacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_equipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txt_servico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addComponent(txt_defeito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txt_valor_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(cb_tecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(714, 197));

        txt_pesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pesquisarKeyReleased(evt);
            }
        });

        tb_os.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tb_os.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_osMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_os);

        cb_opcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tipo", "situação", "descrição", "equipamento", "defeito", "servico", "tecnico" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(cb_opcao, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_opcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/SystemOs/icons/add.png"))); // NOI18N
        btn_novo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_novo.setPreferredSize(new java.awt.Dimension(40, 40));
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        jLabel13.setText("Novo");

        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/SystemOs/icons/Save.png"))); // NOI18N
        btn_salvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_salvar.setEnabled(false);
        btn_salvar.setPreferredSize(new java.awt.Dimension(40, 40));
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        jLabel14.setText("Salvar");

        btn_alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/SystemOs/icons/edit.png"))); // NOI18N
        btn_alterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_alterar.setPreferredSize(new java.awt.Dimension(40, 40));
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        jLabel15.setText("Alterar");

        btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/SystemOs/icons/delete.png"))); // NOI18N
        btn_excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_excluir.setPreferredSize(new java.awt.Dimension(40, 40));
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        jLabel16.setText("Excluir");

        btn_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/SystemOs/icons/print.png"))); // NOI18N
        btn_imprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_imprimir.setPreferredSize(new java.awt.Dimension(40, 40));
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });

        jLabel17.setText("Imprimir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btn_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)))
                .addGap(170, 170, 170))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        setBounds(0, 0, 769, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pesquisar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisar_clienteActionPerformed
        TelaClienteOs clienteOs = new TelaClienteOs();
        TelaInicial.desktop.add(clienteOs);
        clienteOs.setVisible(true);
    }//GEN-LAST:event_btn_pesquisar_clienteActionPerformed

    private void txt_pesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesquisarKeyReleased
        String pesquisar = txt_pesquisar.getText().trim();
        String opcao = "";

        switch (cb_opcao.getSelectedIndex()) {
            case 0:
                opcao = "tipo";
                break;
            case 1:
                opcao = "situacao";
                break;
            case 2:
                opcao = "descricao";
                break;
            case 3:
                opcao = "equipamento";
                break;
            case 4:
                opcao = "defeito";
                break;
            case 5:
                opcao = "servico";
                break;
            case 6:
                opcao = "tecnico";

        }
        String sql = "SELECT * FROM tbos WHERE " + opcao + " LIKE '%" + pesquisar + "%'  ";
        tb_os.setModel(new OsTableModel(new OsDal().listarTodos(sql)));
    }//GEN-LAST:event_txt_pesquisarKeyReleased

    private void tb_osMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_osMouseClicked
        // TODO add your handling code here:
        OsDal dal = new OsDal();
        String tipo, codCliSql;

        txt_os.setText(tb_os.getValueAt(tb_os.getSelectedRow(), COL_COD_OS).toString());
        txt_data.setText(tb_os.getValueAt(tb_os.getSelectedRow(), COL_DATA_OS).toString());

        tipo = tb_os.getValueAt(tb_os.getSelectedRow(), COL_TIPO_OS).toString();
        if (tipo.equals("Orçamento")) {
            rb_orcamento.setSelected(true);
        } else {
            rb_ordem_servico.setSelected(true);
        }

        cb_situacao.setSelectedItem(tb_os.getValueAt(tb_os.getSelectedRow(), COL_SITUACAO_OS).toString());
        txt_equipamento.setText(tb_os.getValueAt(tb_os.getSelectedRow(), COL_EQUIPAMENTO_OS).toString());
        txt_servico.setText(tb_os.getValueAt(tb_os.getSelectedRow(), COL_SERVICO_OS).toString());
        cb_tecnico.setSelectedItem(tb_os.getValueAt(tb_os.getSelectedRow(), COL_TECNICO_OS).toString());
        txt_area_descricao.setText(tb_os.getValueAt(tb_os.getSelectedRow(), COL_DESCRICAO_OS).toString());
        txt_defeito.setText(tb_os.getValueAt(tb_os.getSelectedRow(), COL_DEFEITO_OS).toString());
        txt_valor_total.setText(tb_os.getValueAt(tb_os.getSelectedRow(), COL_VALOR_OS).toString());
        txt_cod_cliente.setText(tb_os.getValueAt(tb_os.getSelectedRow(), COL_COD_CLIENTE_OS).toString());

        codCliSql = txt_cod_cliente.getText();
        dal.valorCliente(codCliSql);

        txt_nome.setText(nome);
        txt_telefone.setText(telefone);

        btn_salvardesabilitado();
        desabilitarCampo();
    }//GEN-LAST:event_tb_osMouseClicked

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        // TODO add your handling code here:

        limparCampo();
        habilitarCampo();
        btn_salvarHabilitado();
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        // TODO add your handling code here:
        String tipos = "";

        if (txt_os.getText().equals("")) {
            //se o campo codigo estiver vazio insere um novo cliente

            Os os = new Os();
            OsDal osDal = new OsDal();

            if (txt_cod_cliente.getText().equals("")
                    || txt_area_descricao.getText().equals("")
                    || txt_equipamento.getText().equals("")) {

                JOptionPane.showMessageDialog(null, "Exite campos vazio, preencha todos os campos");

            } else {

                //verifica se o botão (radioButton) rb_orcamento esta selecionado
                //e atribui o valor a variavel tipos
                if (rb_orcamento.isSelected()) {
                    tipos = "Orçamento";
                } else {
                    tipos = "Ordem de serviço";
                }
                os.setTipo(tipos);

                os.setSituacao(cb_situacao.getSelectedItem().toString());
                os.setEquipamento(txt_equipamento.getText());
                os.setServico(txt_servico.getText());

                os.setTecnico((String) cb_tecnico.getSelectedItem());
                os.setDescricao(txt_area_descricao.getText());
                os.setDefeito(txt_defeito.getText());
                os.setValor(txt_valor_total.getText());
                os.setCod_cliente(Integer.parseInt(txt_cod_cliente.getText()));
                osDal.setCodUser(nomeUser);
                osDal.inserir(os);

                String sql = "SELECT * FROM tbos";
                tb_os.setModel(new OsTableModel(new OsDal().listarTodos(sql)));
                limparCampo();
                obterValor();
                btn_salvardesabilitado();

                desabilitarCampo();
            }
        } else {
            //altera o usuario
            if (txt_cod_cliente.getText().equals("")
                    || txt_area_descricao.getText().equals("")
                    || txt_equipamento.getText().equals("")) {

                JOptionPane.showMessageDialog(null, "Exite campos vazio, preencha todos os campos");

            } else {
                Os os = new Os();
                OsDal osDal = new OsDal();

                if (rb_orcamento.isSelected()) {
                    tipos = "Orçamento";
                } else {
                    tipos = "Ordem de serviço";
                }
                os.setTipo(tipos);

                os.setSituacao(cb_situacao.getSelectedItem().toString());

                os.setEquipamento(txt_equipamento.getText());
                os.setServico(txt_servico.getText());
                os.setTecnico((String) cb_tecnico.getSelectedItem());
                os.setDescricao(txt_area_descricao.getText());
                os.setDefeito(txt_defeito.getText());
                os.setValor(txt_valor_total.getText());
                os.setCod_cliente(Integer.parseInt(txt_cod_cliente.getText()));
                os.setCodigo(Integer.parseInt(txt_os.getText()));

                osDal.alterar(os);
                String sql = "SELECT * FROM tbos";
                tb_os.setModel(new OsTableModel(new OsDal().listarTodos(sql)));

                btn_salvardesabilitado();
                desabilitarCampo();

            }
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        // TODO add your handling code here:
        btn_salvarHabilitado();
        habilitarCampo();
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        OsDal osDal = new OsDal();
        int id = Integer.parseInt(txt_os.getText());
        int confirma = JOptionPane.showConfirmDialog(null,
                "Tem certeza que deseja excluir?",
                "Atenção", JOptionPane.YES_NO_OPTION);

        if (confirma == JOptionPane.YES_OPTION) {
            osDal.excluir(id);
            String sql = "SELECT * FROM tbos";
            tb_os.setModel(new OsTableModel(new OsDal().listarTodos(sql)));
            limparCampo();
            osDal.ultimoCampo();
            obterValor();
            btn_salvardesabilitado();

        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        // TODO add your handling code here:
        int confirma = JOptionPane.showConfirmDialog(null, "imprimir Ordem de Serviços?",
                "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            OsDal dal = new OsDal();
            dal.gerarRelatorio(txt_os);
        }
    }//GEN-LAST:event_btn_imprimirActionPerformed

    private void btn_salvardesabilitado() {
        btn_novo.setEnabled(true);
        btn_alterar.setEnabled(true);
        btn_excluir.setEnabled(true);
        btn_imprimir.setEnabled(true);
        btn_salvar.setEnabled(false);
    }

    private void btn_salvarHabilitado() {
        btn_novo.setEnabled(false);
        btn_alterar.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_imprimir.setEnabled(false);
        btn_salvar.setEnabled(true);
    }

    private void limparCampo() {
        txt_os.setText("");
        txt_data.setText("");
        rb_orcamento.setSelected(true);
        txt_cod_cliente.setText("");
        txt_nome.setText("");
        txt_telefone.setText("");
        cb_situacao.setSelectedIndex(0);
        txt_equipamento.setText("");
        txt_servico.setText("");
        txt_defeito.setText("");
        cb_tecnico.setSelectedIndex(0);
        txt_area_descricao.setText("");
        txt_valor_total.setText("");
    }

    private void habilitarCampo() {
        rb_orcamento.setEnabled(true);
        rb_ordem_servico.setEnabled(true);
        cb_situacao.setEnabled(true);
        txt_equipamento.setEnabled(true);
        txt_servico.setEnabled(true);
        txt_defeito.setEnabled(true);
        cb_tecnico.setEnabled(true);
        txt_area_descricao.setEnabled(true);
        txt_valor_total.setEnabled(true);
        btn_pesquisar_cliente.setEnabled(true);
    }

    private void desabilitarCampo() {
        rb_orcamento.setEnabled(false);
        rb_ordem_servico.setEnabled(false);
        cb_situacao.setEnabled(false);
        txt_equipamento.setEnabled(false);
        txt_servico.setEnabled(false);
        txt_defeito.setEnabled(false);
        cb_tecnico.setEnabled(false);
        txt_area_descricao.setEnabled(false);
        txt_valor_total.setEnabled(false);
        btn_pesquisar_cliente.setEnabled(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bt_group_tipo;
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_pesquisar_cliente;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JComboBox<String> cb_opcao;
    private javax.swing.JComboBox<String> cb_situacao;
    private javax.swing.JComboBox<String> cb_tecnico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rb_orcamento;
    private javax.swing.JRadioButton rb_ordem_servico;
    public static javax.swing.JTable tb_os;
    private javax.swing.JTextArea txt_area_descricao;
    public static javax.swing.JTextField txt_cod_cliente;
    private javax.swing.JTextField txt_data;
    private javax.swing.JTextField txt_defeito;
    private javax.swing.JTextField txt_equipamento;
    public static javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_os;
    private javax.swing.JTextField txt_pesquisar;
    private javax.swing.JTextField txt_servico;
    public static javax.swing.JTextField txt_telefone;
    private javax.swing.JFormattedTextField txt_valor_total;
    // End of variables declaration//GEN-END:variables
}
