
package br.com.SystemOs.view;

import br.com.SystemOs.constantes.ICliente;
import br.com.SystemOs.dal.ClienteDal;
import br.com.SystemOs.table.ClienteTableModel;




public class TelaClienteOs extends javax.swing.JInternalFrame implements ICliente.IConst {

    /**
     * Creates new form TelaClienteOs
     */
    public TelaClienteOs() {
        initComponents();
        String sql = "SELECT * FROM tbcliente";
        tb_cliente.setModel(new ClienteTableModel(new ClienteDal().listarTodos(sql)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_opcao = new javax.swing.JComboBox<>();
        txt_pesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_cliente = new javax.swing.JTable();

        setClosable(true);

        cb_opcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Telefone", "Email" }));

        txt_pesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pesquisarKeyReleased(evt);
            }
        });

        tb_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tb_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_clienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_cliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(cb_opcao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_opcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        setBounds(0, 0, 700, 325);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_pesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesquisarKeyReleased
        // TODO add your handling code here:
        String valor = txt_pesquisar.getText().trim();
        String tipo = "";

        switch (cb_opcao.getSelectedIndex()) {
            case 0:
            tipo = "nomecli";
            break;
            case 1:
            tipo = "fonecli";
            break;
            case 2:
            tipo = "emailcli";

        }
        String sql = "SELECT * FROM tbcliente WHERE " + tipo + " LIKE '%" + valor + "%'  ";
        tb_cliente.setModel(new ClienteTableModel(new ClienteDal().listarTodos(sql)));
    }//GEN-LAST:event_txt_pesquisarKeyReleased

    private void tb_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_clienteMouseClicked
        
        //ao clicar em um determinado valor na tabela preenche os campos de texto(TextView)
        TelaOs.txt_cod_cliente.setText(tb_cliente.getValueAt(tb_cliente.getSelectedRow(), COL_CODIGO_CLIENTE).toString());
        TelaOs.txt_nome.setText(tb_cliente.getValueAt(tb_cliente.getSelectedRow(), COL_NOME_CLIENTE).toString());
        TelaOs.txt_telefone.setText(tb_cliente.getValueAt(tb_cliente.getSelectedRow(), COL_TELEFONE_CLIENTE).toString());

        this.dispose();
    }//GEN-LAST:event_tb_clienteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_opcao;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tb_cliente;
    private javax.swing.JTextField txt_pesquisar;
    // End of variables declaration//GEN-END:variables
}
